# Generated by Django 3.1.1 on 2021-05-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0007_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='testFields.CartProduct'),
        ),
    ]
