# Generated by Django 3.1.1 on 2021-05-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0008_auto_20210515_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(default='', to='testFields.CartProduct'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
    ]
