# Generated by Django 3.1.1 on 2021-05-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0009_auto_20210515_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
