# Generated by Django 3.1.1 on 2021-05-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0010_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
