# Generated by Django 3.1.1 on 2021-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0011_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(default=''),
        ),
    ]
