# Generated by Django 3.1.1 on 2021-05-16 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0013_order_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_ordering',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
