# Generated by Django 3.1.1 on 2021-05-16 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0014_order_date_of_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 5, 9)),
        ),
    ]
