# Generated by Django 3.1.1 on 2021-05-16 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testFields', '0015_order_date_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 5, 23)),
        ),
    ]
